[package]
name = "kzg_prover"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kimchi = { git = "https://github.com/lambdaclass/proof-systems", branch = "witness_computation", features = [
    "keccak-sponges",
    "bn254",
] }
poly-commitment = { git = "https://github.com/lambdaclass/proof-systems", branch = "witness_computation" }
serde_json = "1"
serde = { version = "1", features = ["derive"] }
ark-ec = { version = "0.3.0", features = ["parallel"] }
ark-bn254 = "0.3.0"
rmp-serde = "1.1.2"
