name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]

jobs:
  kzg_prover:
    uses: lambdaclass/mina_bridge/.github/workflows/rust_ci.yaml@ci
    with:
      directory: ${{github.job}}

  public_input_gen:
    uses: lambdaclass/mina_bridge/.github/workflows/rust_ci.yaml@ci
    with:
      directory: ${{github.job}}

  verify_circuit_tests:
    uses: lambdaclass/mina_bridge/.github/workflows/rust_ci.yaml@ci
    with:
      directory: ${{github.job}}

  evm_bridge:
    name: Build and test EVM bridge
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./evm_bridge
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Set up dependencies
        run: npm ci

      - name: Run npm build
        run: npm run build

      - name: Run npm test
        run: npm run test
