name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]

jobs:
  kzg_prover:
    name: KZG Prover
    uses: ./.github/workflows/rust_ci.yaml
    with:
      directory: kzg_prover
      skip_run: true

  public_input_gen:
    name: Public input generation
    uses: ./.github/workflows/rust_ci.yaml
    with:
      directory: public_input_gen

  verify_circuit_tests:
    name: Verifying circuit Rust tests
    uses: ./.github/workflows/rust_ci.yaml
    with:
      directory: verify_circuit_tests

  evm_bridge:
    name: Build and test EVM bridge
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./evm_bridge
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      
      - name: Set Mina monorepo commit env var
        run: echo "MINA_COMMIT=$(cd $GITHUB_WORKSPACE && git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: latest
        
      - name: Install rust toolchain for Mina monorepo
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly-2022-09-12-x86_64-unknown-linux-gnu
      
      - name: Install opam dependencies
        run: sudo apt-get install opam liblmdb-dev && opam init

      - name: Set up dependencies
        run: npm ci

      - name: Cache opam packages
        uses: actions/cache@v3
        with:
          key: opam
          path: /home/runner/.opam
      
      - name: Cache Mina monorepo packages
        uses: actions/cache@v3
        with:
          key: mina_monorepo-${{ env.MINA_COMMIT }}
          path: /home/runner/mina_monorepo

      - name: Run npm build
        run: npm run build

      - name: Run npm test
        run: npm run test
