name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]

jobs:
  kzg_prover:
    name: KZG Prover
    uses: lambdaclass/mina_bridge/.github/workflows/rust_ci.yaml@ci
    with:
      directory: kzg_prover

  public_input_gen:
    name: Public input generation
    uses: lambdaclass/mina_bridge/.github/workflows/rust_ci.yaml@ci
    with:
      directory: public_input_gen

  verify_circuit_tests:
    name: Verifying circuit Rust tests
    uses: lambdaclass/mina_bridge/.github/workflows/rust_ci.yaml@ci
    with:
      directory: verify_circuit_tests

  evm_bridge:
    name: Build and test EVM bridge
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./evm_bridge
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Set up dependencies
        run: npm ci

      - name: Run npm build
        run: npm run build

      - name: Run npm test
        run: npm run test
