name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]

jobs:
  kzg_prover:
    name: Check, test and fmt KZG prover
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./kzg_prover
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install rust stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Install nextest
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest

      - name: Set up cargo cache
        uses: Swatinem/rust-cache@v2

      - name: Run cargo check
        run: cargo check --workspace

      - name: Run nextest
        run: cargo nextest run --workspace --all-targets --no-fail-fast

      - name: Run rustfmt
        run: cargo fmt --all --check

      - name: Run clippy
        run: cargo clippy --workspace --all-targets

  evm_bridge:
    name: Build and test EVM bridge
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./evm_bridge
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Set up dependencies
        run: npm ci

      - name: Run npm build
        run: npm run build

      - name: Run npm test
        run: npm run test
